<a href="https://colab.research.google.com/github/areebaarshadqureshi/Data-Science-Journey-CampusX/blob/main/02-Numpy/03-Numpy-Tricks/Numpy_Tricks_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([42,  3, 42, 12, 56,  3, 19, 69,  1, 69, 17, 78, 77, 76, 92])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[30,  5,  9, 72],
       [96, 69, 16, 14],
       [54, 91, 25, 46],
       [66, 26, 19, 61],
       [80,  1,  4, 21],
       [48, 66, 59, 51]])

In [ ]:
#------------np.sort() returns numpy array
print(np.sort(a))
print()
print(np.sort(a)[::-1])

[ 1  3  3 12 17 19 42 42 56 69 69 76 77 78 92]

[92 78 77 76 69 69 56 42 42 19 17 12  3  3  1]


In [ ]:
###row wise sort
print(np.sort(b))
print()
##columns wise
print(np.sort(b,axis=0))


[[ 5  9 30 72]
 [14 16 69 96]
 [25 46 54 91]
 [19 26 61 66]
 [ 1  4 21 80]
 [48 51 59 66]]

[[30  1  4 14]
 [48  5  9 21]
 [54 26 16 46]
 [66 66 19 51]
 [80 69 25 61]
 [96 91 59 72]]


### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
print(np.append(a,200)) ##np.append(arrayname,number you want to append)
print(np.append(b,np.ones((b.shape[0],1)),axis=1))

[ 42   3  42  12  56   3  19  69   1  69  17  78  77  76  92 200]
[[30.  5.  9. 72.  1.]
 [96. 69. 16. 14.  1.]
 [54. 91. 25. 46.  1.]
 [66. 26. 19. 61.  1.]
 [80.  1.  4. 21.  1.]
 [48. 66. 59. 51.  1.]]


print(np.append(b,))

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
print(np.concatenate((c,d),axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
print(np.concatenate((c,d),axis=1))

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
a

array([42,  3, 42, 12, 56,  3, 19, 69,  1, 69, 17, 78, 77, 76, 92])

In [ ]:
print(np.expand_dims(a,axis=0))
print(np.expand_dims(a,axis=1))

###

[[42  3 42 12 56  3 19 69  1 69 17 78 77 76 92]]
[[42]
 [ 3]
 [42]
 [12]
 [56]
 [ 3]
 [19]
 [69]
 [ 1]
 [69]
 [17]
 [78]
 [77]
 [76]
 [92]]


### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([42,  3, 42, 12, 56,  3, 19, 69,  1, 69, 17, 78, 77, 76, 92])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

#return index position

(array([ 4,  7,  9, 11, 12, 13, 14]),)

In [ ]:
# replace all values > 50 with 0
a[np.where(a>50)]=0
print(a)

[42  3 42 12  0  3 19  0  1  0 17  0  0  0  0]


In [ ]:
##np.where(cond,true,false)

np.where(a>50,0,a)

array([42,  3, 42, 12,  0,  3, 19,  0,  1,  0, 17,  0,  0,  0,  0])

In [ ]:
print(a)
np.where(a%2==0,0,a)

[42  3 42 12  0  3 19  0  1  0 17  0  0  0  0]


array([ 0,  3,  0,  0,  0,  3, 19,  0,  1,  0, 17,  0,  0,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a=np.random.randint(1,100,10)
a


array([96, 35, 25, 27, 44, 16, 37, 63, 67, 55])

In [ ]:
print(np.argmax(a))#--------------return index position
print(np.argmin(a))
#

9
8


In [ ]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[15, 85, 79, 10],
       [35,  6, 43, 54],
       [98, 12, 57, 27],
       [78, 32, 35, 52],
       [63, 99, 54, 58],
       [16, 75, 13, 83]])

In [ ]:
print(np.argmax(b,axis=0))
print(np.argmax(b,axis=1))

[5 4 1 1]
[1 2 1 1 1 0]


### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([79, 68, 67, 31, 65, 88, 66, 85, 18, 89])

In [ ]:
np.cumsum(a)

array([ 79, 147, 214, 245, 310, 398, 464, 549, 567, 656])

In [ ]:
b

array([[68, 71, 56, 70],
       [56, 69, 83, 74],
       [41, 61, 41,  4],
       [62, 85, 77, 37],
       [58, 97, 61, 30],
       [78, 16, 15, 72]])

In [ ]:
np.cumsum(b,axis=1) ##axis should be mandotary for 2D

array([[ 68, 139, 195, 265],
       [ 56, 125, 208, 282],
       [ 41, 102, 143, 147],
       [ 62, 147, 224, 261],
       [ 58, 155, 216, 246],
       [ 78,  94, 109, 181]])

In [ ]:
#np.cumprod
np.cumprod(a)

array([                79,               5372,             359924,
                 11157644,          725246860,        63821723680,
            4212233762880,    358039869844800,   6444717657206400,
       573579871491369600])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([79, 68, 67, 31, 65, 88, 66, 85, 18, 89])

In [ ]:
np.percentile(a,100) ###100----maximum,0---minimum

np.float64(89.0)

In [ ]:
np.percentile(a,50)

np.float64(67.5)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([1, 1, 0, 5, 3]), array([  0,  20,  40,  60,  80, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
##answer will be between -1 to 1
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a


array([79, 68, 67, 31, 65, 88, 66, 85, 18, 89])

In [ ]:
items = [10,20,30,40,50,68,70,80,90,100] ##items to find
print(np.isin(a,items))
print(a[np.isin(a,items)])
#np.isin use to find multiple values

[False  True False False False False False False False False]
[68]


### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
a

array([79, 68, 67, 31, 65, 88, 66, 85, 18, 89])

In [ ]:
np.flip(a)##reverse

array([89, 18, 85, 66, 88, 65, 31, 67, 68, 79])

In [ ]:
b

array([[68, 71, 56, 70],
       [56, 69, 83, 74],
       [41, 61, 41,  4],
       [62, 85, 77, 37],
       [58, 97, 61, 30],
       [78, 16, 15, 72]])

In [ ]:
np.flip(b)#first------row,then column

array([[72, 15, 16, 78],
       [30, 61, 97, 58],
       [37, 77, 85, 62],
       [ 4, 41, 61, 41],
       [74, 83, 69, 56],
       [70, 56, 71, 68]])

In [ ]:
import numpy as np

np.flip(b,axis=0)

array([[16, 75, 13, 83],
       [63, 99, 54, 58],
       [78, 32, 35, 52],
       [98, 12, 57, 27],
       [35,  6, 43, 54],
       [15, 85, 79, 10]])

In [ ]:
np.flip(b,axis=1)

array([[10, 79, 85, 15],
       [54, 43,  6, 35],
       [27, 57, 12, 98],
       [52, 35, 32, 78],
       [58, 54, 99, 63],
       [83, 13, 75, 16]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
a

array([96, 35, 25, 27, 44, 16, 37, 63, 67, 55])

In [ ]:
##change 96 with 102,35 with 42
np.put(a,[0,1],[102,42]) #(changinig array,[indexes of elements],[numbers you want])
a ##permenantly change

array([102,  42,  25,  27,  44,  16,  37,  63,  67, 102])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
a

array([102,  42,  25,  27,  44,  16,  37,  63,  67, 102])

In [ ]:
np.delete(a,0) #(array, index you want to delete)
np.delete(a,[0,2])

array([ 42,  27,  44,  16,  37,  63,  67, 102])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d
- answer would be in nmupy array

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.setxor1d(m,n) #remove common elements from both sets

array([1, 2, 6, 7])

In [ ]:
np.in1d(m,1) ##(set,element you want to search)
m[np.in1d(m,1)]

/tmp/ipython-input-21-2603575366.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1) ##(set,element you want to search)
/tmp/ipython-input-21-2603575366.py:2: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
a

array([102,  42,  25,  27,  44,  16,  37,  63,  67, 102])

In [ ]:
##palce values between 25 to 75
np.clip(a,25,75)  ##higher values replace with 75 and smaller with 25

array([75, 42, 25, 27, 44, 25, 37, 63, 67, 75])